name: Generate Pac-Man

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Andreyka445
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
